global:
  scrape_interval: 10s
  external_labels:
    monitor: "corda-network"
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node1:8080", "node2:8080"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance
